-- ============================================================================
-- FRAGANTI — Schema de Supabase para el catálogo con stock en vivo
-- Corre esto en: tu proyecto de Supabase → SQL Editor → New query → Run
-- ============================================================================

create table if not exists public.perfumes (
  id bigint generated by default as identity primary key,
  name text not null default '',
  inspirado_en text default '',
  family text not null default 'Floral',
  image text not null default '',
  is_new boolean default false,
  notas_corta text default '',
  notas jsonb not null default '{"salida":[],"corazon":[],"fondo":[]}'::jsonb,
  formatos jsonb not null default '{
    "completo": {"disponible": true, "precio": "", "stock": 0},
    "decant5": {"disponible": false, "precio": "", "stock": 0},
    "decant10": {"disponible": false, "precio": "", "stock": 0}
  }'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Actualiza "updated_at" solo cada vez que se edita una fila.
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists perfumes_set_updated_at on public.perfumes;
create trigger perfumes_set_updated_at
before update on public.perfumes
for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- Seguridad (Row Level Security)
-- La tienda pública necesita LEER el catálogo sin iniciar sesión.
-- Solo un usuario autenticado (tú, el admin) puede crear/editar/borrar.
-- ----------------------------------------------------------------------------

alter table public.perfumes enable row level security;

drop policy if exists "Perfumes son publicos para lectura" on public.perfumes;
create policy "Perfumes son publicos para lectura"
  on public.perfumes for select
  using (true);

drop policy if exists "Solo admin autenticado puede insertar" on public.perfumes;
create policy "Solo admin autenticado puede insertar"
  on public.perfumes for insert
  to authenticated
  with check (true);

drop policy if exists "Solo admin autenticado puede actualizar" on public.perfumes;
create policy "Solo admin autenticado puede actualizar"
  on public.perfumes for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Solo admin autenticado puede borrar" on public.perfumes;
create policy "Solo admin autenticado puede borrar"
  on public.perfumes for delete
  to authenticated
  using (true);
