-- Inserta los 21 perfumes reales de FRAGANTI en Supabase.
-- Corre esto DESPUÉS de crear la tabla (schema.sql), en el SQL Editor de Supabase.

insert into public.perfumes (id, name, inspirado_en, family, image, is_new, notas_corta, notas, formatos) values
  (1, 'Lattafa Yara Elixir', '', 'Oriental', 'yara elixir.jpg', true, 'femenina, avainillada', '{"salida": ["S''mores de fresa", "Grosellas negras"], "corazon": ["Jazmin", "Flor de azahar de naranjo"], "fondo": ["Vainilla", "Caramelo", "ámbar"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$195.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (2, 'Arabiyat Prestige Marwa', 'Louis Vuitton Imagination', 'Fresca', 'marwa.jpg', true, 'citrico', '{"salida": ["Bergamota", "Limón", "Naranja siciliana"], "corazon": ["Jengibre", "Canela", "Neroli", "jabón"], "fondo": ["Ambroxán", "Té negro", "Madera de gaiac"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$280.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (3, 'Versace Eros EDP TESTER', '', 'Cítrica', 'versace eros.jpg', true, 'amaderada, fresca', '{"salida": ["Menta", "Manzana acaramelada", "Limón", "Mandarina"], "corazon": ["Geranio", "Ambroxán", "Esclarea"], "fondo": ["Cedro", "Vainilla", "Sándalo", "Naranja amarga", "cuero"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$300.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (4, 'Odyssey Go Mango', '', 'Fresca', 'odyssey gm.jpg', true, 'tropical, unisex', '{"salida": ["Limón", "Jengibre", "Pimienta Rosa"], "corazon": ["Mango", "Madera seca", "Haba tonka"], "fondo": ["ámbar", "Vainilla", "Nota de frutos secos", "Madera de gaiac"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$235.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (5, 'Club de Nuit Intense Parfum Limited Edition', 'Creed Aventus', 'Cítrica', 'cdn i.jpg', true, 'cuero, ahumada', '{"salida": ["Limón", "Piña ahumada", "Lima", "Pimienta negra", "Pimienta rosa"], "corazon": ["Jazmin", "Rosa", "Lirio de los valles"], "fondo": ["Cuero", "Pachulí", "Cedro", "ámbar gris", "Ambroxán"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$380.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (6, 'Lattafa Art of Universe', '', 'Fresca', 'art of universe.jpg', true, 'fresca, atalcada', '{"salida": ["Mandarina", "Jengibre", "Bergamota", "Menta"], "corazon": ["Pera", "Flor de azahar del naranjo"], "fondo": ["ámbar", "Cedro", "Almizcle"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$290.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (7, 'Amber Oud Gold Edition ', 'XERJOFF Erba Pura', 'Oriental', 'amber oud ge.jpg', true, 'dulce, afrutado', '{"salida": ["Begamota", "Notas verdes"], "corazon": ["Melón", "Piña", "ámbar", "Acorde goloso"], "fondo": ["Vainilla", "Notas amaderadas", "Almizcle"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$240.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (8, 'Arabiyat Prestige Raspberry Ripple', '', 'Floral', 'arabiyat prestige rr.jpg', true, 'afrutado, dulce', '{"salida": ["Marshmellow", "Grosellas negras", "Fresa"], "corazon": ["Frambuesa", "Magnolia"], "fondo": ["Vainilla", "Caramelo", "Musgo"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$230.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (9, 'Arabiyat Prestige Bahiya Garnet', '', 'Floral', 'bahiya garnet.jpg', true, 'acerezado, dulce', '{"salida": [], "corazon": [], "fondo": []}'::jsonb, '{"completo": {"disponible": true, "precio": "$250.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (10, 'Club de Nuit Sillage', 'Creed Silver Mountain Water', 'Fresca', 'cdb sillage.jpg', true, 'cítrico, floral', '{"salida": ["Bergamota", "Limón", "Lima", "Hojas de violeta", "Grosellas negras", "Jengibre"], "corazon": ["Rosa", "Iris", "Jazmín"], "fondo": ["Ambroxan", "Almizcle", "Sándalo", "Cedro"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$240.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (11, 'Club de Nuit Urban Man Elixir', 'Dior Sauvage', 'Fresca', 'cdn ume.jpg', true, 'ámbar, aromática', '{"salida": ["Bergamota", "Pimienta Rosa", "Flor de azahar del naranjo", "Jazmin"], "corazon": ["Lavanda", "Elemí", "Geranio", "Vetiver", "Azafrán"], "fondo": ["ámbar", "Cedro", "Pachulí", "Ambroxán"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$240.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (12, 'Dolce Gabbana Light Blue', '', 'Fresca', 'dyg lb.jpg', true, 'cítrico, marino', '{"salida": ["Toronja", "Mandarina"], "corazon": ["Agua de mar", "Enebro"], "fondo": ["Almizcle", "Amberwood"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$335.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (13, 'Hawas For Him', 'Paco Rabanne Invictus ', 'Fresca', 'hawas fh.jpg', true, 'acuática, afrutada', '{"salida": ["Manzana verde", "Bergamota", "Limón", "Canela"], "corazon": ["Notas acuosas", "Ciruela", "Flor de azahar del naranjo", "Cardamomo"], "fondo": ["Ambar gris", "Pachulí", "Trozos de madera a la deriva"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$230.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (14, 'Lattafa Her Confession', '', 'Oriental', 'her confession.jpg', true, 'avainillado, floral', '{"salida": ["Canela", "Mystikal"], "corazon": ["Nardos", "Jazmín", "Incienso"], "fondo": ["Vainilla", "Almizcle", "Haba tonka"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$220.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (15, 'Lattafa His Confession', '', 'Oriental', 'his confession.jpg', true, 'avainillado, especiado', '{"salida": ["Canela", "Lavanda", "Mandarina"], "corazon": ["Iris", "Benjuí", "Ciprés"], "fondo": ["Vainilla", "Haba tonka", "ámbar", "Incienso", "Cedro", "Pachulí"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$220.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (16, 'Issey Miyake Pour Homme', '', 'Cítrica', 'issey miyake.jpg', true, 'fresco, verde', '{"salida": ["Yuzu", "Limón", "Bergamota", "Cedrón", "Mandarina", "Salvia", "Cilantro"], "corazon": ["Flor de loto azul", "Lirio de los valles", "Nuez moscada", "Geranio bourbon", "Azafrán", "Canela de Ceylan"], "fondo": ["Vetiver de Tahití", "Almizcle", "Cedro", "ámbar", "Tabaco"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$280.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (17, 'Moschino TOY BOY TESTER', '', 'Floral', 'toyboy.jpg', true, 'rosas, amaderado', '{"salida": ["Pimienta rosa", "Pera", "Nuez moscada", "Bergamota"], "corazon": ["Rosa", "Clavo de olor", "Magnolia", "Lino"], "fondo": ["Vetiver de Haití", "Sándalo", "ámbar"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$235.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (18, 'Supremacy Not Only Intense', 'Creed Aventus', 'Amaderada', 'supremacy noi.jpg', true, 'afrutado, musgoso', '{"salida": ["Grosellas negras", "Begamota", "Manzana verde"], "corazon": ["Musgo de roble", "Pachulí", "Lavanda"], "fondo": ["ámbar gris", "Almizcle", "Azafrán"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$340.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (19, 'Odyssey Home White', 'Armani Stronger With YOU', 'Amaderada', 'odyssey hw.jpg', true, 'dulce, aromático', '{"salida": ["Cardamomo", "Pimienta rosa", "Menta"], "corazon": ["Notas acuáticas", "Salvia", "Piña"], "fondo": ["Vainilla", "Amberwood", "Cedro"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$220.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (20, 'Odyssey BA HA MAS', '', 'Fresca', 'o bahamas.jpg', true, 'marino, acuático', '{"salida": ["Melón", "Algas", "Sal", "Pera", "Manzana verde", "Ciruela"], "corazon": ["Notas acuáticas", "Musgo de roble", "Incienso"], "fondo": ["Azúcar", "Almizcle", "ámbar", "Cedro"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$245.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb),
  (21, 'Orientica Premium Royal Bleu', 'Parfums de Marly Layton', 'Oriental', 'orientica rb.jpg', true, 'amaderada, especiada', '{"salida": ["Manzana verde", "Lavanda", "Mandarina", "Pimienta", "Bergamota"], "corazon": ["Cardamomo", "Geranio", "Violeta", "Jazmín"], "fondo": ["Vainilla", "Sándalo", "Madera de gaiac", "Pachulí", "Almizcle"]}'::jsonb, '{"completo": {"disponible": true, "precio": "$390.000", "stock": 5}, "decant5": {"disponible": false, "precio": "", "stock": 0}, "decant10": {"disponible": false, "precio": "", "stock": 0}}'::jsonb);

-- Reinicia el contador de ids para que el próximo perfume que agregues
-- desde el panel no choque con estos 21.
select setval(pg_get_serial_sequence('public.perfumes', 'id'), (select max(id) from public.perfumes));